INSERT INTO ayudas (description, created_at, updated_at) VALUES
('Scholarship Program', NOW(), NOW()),
('Medical Assistance', NOW(), NOW()),
('Food Aid', NOW(), NOW()),
('Disaster Relief', NOW(), NOW()),
('Housing Assistance', NOW(), NOW()),
('Employment Support', NOW(), NOW()),
('Utility Bill Assistance', NOW(), NOW()),
('Education Grant', NOW(), NOW()),
('Senior Citizen Support', NOW(), NOW()),
('Childcare Support', NOW(), NOW()),
('Livelihood Program', NOW(), NOW()),
('Health Check-Up', NOW(), NOW()),
('Transport Subsidy', NOW(), NOW()),
('Nutrition Program', NOW(), NOW()),
('Cultural Activity Support', NOW(), NOW()),
('Entrepreneurship Grant', NOW(), NOW()),
('Disability Support', NOW(), NOW()),
('Community Development Fund', NOW(), NOW()),
('Emergency Fund', NOW(), NOW()),
('Legal Aid', NOW(), NOW());
