INSERT INTO barangays (name, municity_id, created_at, updated_at) VALUES
('Balon', 3, NOW(), NOW()),
('Barra', 3, NOW(), NOW()),
('Basirang', 3, NOW(), NOW()),
('Bongabong', 3, NOW(), NOW()),
('Buenavista', 3, NOW(), NOW()),
('Cabol-anonan', 3, NOW(), NOW()),
('Cahayag', 3, NOW(), NOW()),
('Camating', 3, NOW(), NOW()),
('Canibungan Proper', 3, NOW(), NOW()),
('Casilak San Agustin', 3, NOW(), NOW()),
('Centro Hulpa (Poblacion)', 3, NOW(), NOW()),
('Centro Napu (Poblacion)', 3, NOW(), NOW()),
('Centro Upper (Poblacion)', 3, NOW(), NOW()),
('Colambutan Bajo', 3, NOW(), NOW()),
('Colambutan Settlement', 3, NOW(), NOW()),
('Duanguican', 3, NOW(), NOW()),
('Gala', 3, NOW(), NOW()),
('Gumbil', 3, NOW(), NOW()),
('Locso-on', 3, NOW(), NOW()),
('Maikay', 3, NOW(), NOW()),
('Maribojoc', 3, NOW(), NOW()),
('Mitugas', 3, NOW(), NOW()),
('Nailon', 3, NOW(), NOW()),
('Namut', 3, NOW(), NOW()),
('Napurog', 3, NOW(), NOW()),
('Pan-ay Diot', 3, NOW(), NOW()),
('San Nicolas', 3, NOW(), NOW()),
('Sebac', 3, NOW(), NOW()),
('Silongon', 3, NOW(), NOW()),
('Sinuza', 3, NOW(), NOW()),
('Taguima', 3, NOW(), NOW()),
('Tigdok', 3, NOW(), NOW()),
('Yahong', 3, NOW(), NOW());
