/*
MySQL Data Transfer
Source Host: localhost
Source Database: asensopinoydb
Target Host: localhost
Target Database: asensopinoydb
Date: 31/07/2024 4:48:50 am
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for members
-- ----------------------------
DROP TABLE IF EXISTS `members`;
CREATE TABLE `members` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `asenso_id` bigint(20) unsigned DEFAULT NULL,
  `lastname` varchar(255) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  `middlename` varchar(255) NOT NULL,
  `birthdate_str` varchar(255) DEFAULT NULL,
  `birthdate` date DEFAULT NULL,
  `birthplace` varchar(255) NOT NULL,
  `sex` varchar(255) NOT NULL,
  `civil_status` varchar(255) NOT NULL,
  `blood_type` varchar(255) NOT NULL,
  `position` varchar(255) NOT NULL,
  `profession` varchar(255) NOT NULL,
  `barangay_id` bigint(20) unsigned NOT NULL,
  `present_address` varchar(255) NOT NULL,
  `mobile_no` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `contact_person` varchar(255) NOT NULL,
  `contact_address` varchar(255) NOT NULL,
  `contact_mobile` varchar(255) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT 1,
  `image_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=208 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `members` VALUES ('1', null, 'SINGIDAS', 'ROLANDO', 'PALAO', 'DEC. 17, 1962', '1962-12-17', 'BASIRANG, TUDELA', 'M', 'MARRIED', '-', 'PUNONG BARANGAY', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9508001582', null, 'JOSEFINA T. SINGIDAS', 'P-3, CAHAYAG, MIS. OCC.', '9507766566', '1', 'Singidas, Rolando P..jpg', null, null);
INSERT INTO `members` VALUES ('2', null, 'GUMAAT', 'JAIME', 'OGAPAY', 'MAR. 03, 1974', '1974-03-03', 'BUENAVISTA, TUDELA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9753073674', null, 'LIZA B. GUMAAT', 'P-3, CAHAYAG, MIS. OCC.', '-', '1', 'Gumaat, Jaime O..jpg', null, null);
INSERT INTO `members` VALUES ('3', null, 'TURSULADO', 'JEMAR', 'BESTO', 'DEC. 25, 1998', '1998-12-25', 'CAHAYAG, TUDELA', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9558477603', null, 'JEAN B. TORSULADO', 'P-4, CAHAYAG, MIS. OCC.', '9558477603', '1', 'Tursulado, Jemar B..jpg', null, null);
INSERT INTO `members` VALUES ('4', null, 'TOSLOLADO', 'DENY', 'HUGO', 'MAY 26, 1985', '1985-05-26', 'CAHAYAG, TUDELA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'MECHANIC', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9057540863', null, 'APPLE MAE FAJARDO', 'CAHAYAG, TUDELA, MIS. OCC.', '9057540836', '1', 'Toslolado, Deny H..jpg', null, null);
INSERT INTO `members` VALUES ('5', null, 'BLANCAR', 'ROBELYN', 'GUMIMOD', 'OCT. 10, 2002', '2002-10-10', 'JOSEFINA, ZAMBO DEL SUR', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9979053615', null, 'MARK ROGIE C. BLANCAR', 'P-3, CAHAYAG, MIS. OCC.', '-', '1', 'Blancar, Robelyn G..jpg', null, null);
INSERT INTO `members` VALUES ('6', null, 'GOMONOD', 'ALBERT', 'ABERGAS', 'AUG. 07, 1987', '1987-08-07', 'CAHAYAG, TUDELA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9639380468', null, 'ELLEN S. GOMONOD', 'P-2, CAHAYAG, MIS. OCC.', '-', '1', 'Gomonod, Albert A..jpg', null, null);
INSERT INTO `members` VALUES ('7', null, 'MAGADAN', 'ELMAR', 'JAMELO', 'APR. 03, 1982', '1982-04-03', 'CAHAYAG, TUDELA', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9121568251', null, '-', '-', '-', '1', 'Magadan, Elmar J..jpg', null, null);
INSERT INTO `members` VALUES ('8', null, 'GALLUR', 'CRISTINA', 'TAGANAHAN', 'JUN. 23, 1974', '1974-06-23', 'BUENAVISTA, TUDELA', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JOEL M. GALLUR', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gallur, Cristina T..jpg', null, null);
INSERT INTO `members` VALUES ('9', null, 'GOMONOD', 'ELSA', 'EGAM', 'OCT. 13, 1978', '1978-10-13', 'OROQUIETA CITY', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9755740318', null, 'JUBY B. GOMONOD', 'P-3, CAHAYAG, MIS. OCC.', '9755740318', '1', 'Gomonod, Elsa E..jpg', null, null);
INSERT INTO `members` VALUES ('10', null, 'MADULA', 'JINGLE', 'BLANCAR', 'DEC. 31, 1978', '1978-12-31', 'SINACABAN, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', '-', '-', null, 'GILBERT E. MADULA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Jingle B..jpg', null, null);
INSERT INTO `members` VALUES ('11', null, 'MACALISANG', 'JESSEL MAE', 'QUIROG', 'JUN. 08, 2002', '2002-06-08', 'LIBERTAD BAJO, SINACABAN', 'F', 'SINGLE', 'B', 'BHW', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9753073674', null, 'CHRISALDE B. GUMAAT', 'P-3, CAHAYAG, MIS. OCC.', '9679572831', '1', 'Macalisang, Jessel Mae Q..jpg', null, null);
INSERT INTO `members` VALUES ('12', null, 'LUMASAG', 'MELRY ', 'MAGADAN', 'OCT. 26, 1978', '1978-10-26', 'CAHAYAG, TUDELA', 'F', 'LIVE-IN', 'O', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'REY J. GUIRNALDO', 'P-4, CAHAYAG, MIS. OCC.', '9380007874', '1', 'Lumasag, Melry  M..jpg', null, null);
INSERT INTO `members` VALUES ('13', null, 'GOMONOD', 'SABINA', 'ABERGAS', 'JUL. 14, 1963', '1963-07-14', 'CENTRO NAPU, TUDELA', 'F', 'WIDOW', 'B', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MARK A. GOMONOD', 'P-2, CAHAYAG, MIS. OCC.', '-', '1', 'Gomonod, Sabina A..jpg', null, null);
INSERT INTO `members` VALUES ('14', null, 'MADLUS', 'NAMERLITO', 'CABATUAN', 'DEC. 07, 1979', '1979-12-07', 'CAHAYAG, TUDELA', 'M', 'MARRIED', 'A+', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9191989852', null, 'GENALYN N. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madlus, Namerlito C..jpg', null, null);
INSERT INTO `members` VALUES ('15', null, 'MADLUS', 'RICKY', 'CABATUAN', 'FEB. 08, 1988', '1988-02-08', 'CAHAYAG, TUDELA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9107285590', null, 'AILEEN A. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '9556250336', '1', 'Madlus, Ricky C..jpg', null, null);
INSERT INTO `members` VALUES ('16', null, 'MADLUS', 'ROSITO', 'CABATUAN', 'MAY 04, 1981', '1981-05-04', 'CAHAYAG, TUDELA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9659650638', null, 'JOCELYN M. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '9051506263', '1', 'Madlus, Rosito D..jpg', null, null);
INSERT INTO `members` VALUES ('17', null, 'GALORIO', 'GINA', 'DAHIS', 'MAY 28, 1967', '1967-05-28', 'POBLACION 4, CLARIN', 'F', '-', 'O', 'BRGY. TREASURER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '936559005', null, 'SHARON R. DAHIS', 'P-6, POB. 4, CLARIN, MIS.OCC.', '-', '1', 'Galorio, Gina D..jpg', null, null);
INSERT INTO `members` VALUES ('18', null, 'GOMONOD', 'BENIGNO', 'SOL', 'NOV. 1, 1957', '1957-11-01', 'CAHAYAG, TUDELA', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9755740318', null, 'ELSA E. GOMONOD', 'P-3, CAHAYAG, MIS. OCC.', '9755740318', '1', 'Gomonod, Benigno S..jpg', null, null);
INSERT INTO `members` VALUES ('19', null, 'GOMONOD', 'APRIL JOHN', 'DURA', 'APR. 16, 1998', '1998-04-16', 'CAHAYAG, TUDELA', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'LIZA D. GOMONOD', 'P-1, CAHAYAG, MIS. OCC.', '9552354794', '1', 'Gomonod, April John D..jpg', null, null);
INSERT INTO `members` VALUES ('20', null, 'GOMONOD', 'AMER', 'BINTULAN', 'APR. 06, 1995', '1995-04-06', 'CAHAYAG, TUDELA', 'M', 'SINGLE', 'B', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'VIRGINIA B. DOMONOD', 'P-2, CAHAYAG, MIS. OCC.', '-', '1', 'Gomonod, Amer B..jpg', null, null);
INSERT INTO `members` VALUES ('21', null, 'PASTERA', 'GREGUI', 'RABAGO', 'APR. 05, 1982', '1982-04-05', 'LALA, LANAO DEL NORTE', 'M', 'MARRIED', 'B+', 'REGISTERED VOTER', 'DRIVER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9958467555', null, 'NENA M. PASTERA', 'P-2, CAHAYAG, MIS. OCC.', '9129507554', '1', 'Pastera, Gregui R..jpg', null, null);
INSERT INTO `members` VALUES ('22', null, 'PARTIA ', 'MAE AN LIEZL', 'LLORONG ', 'JUN. 28, 1985', '1985-06-28', 'TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'VERGIE M. MOLO', 'BALON. TUDELA, MIS. OCC.', '9061802199', '1', 'Partia , Mae An Liezl L..jpg', null, null);
INSERT INTO `members` VALUES ('23', null, 'RAMIL', 'DANIELA', 'MACABANETA', 'JUL. 21, 1956', '1956-07-21', 'BONGABONG, TUDELA, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-1, CAHAYAG, TUDELA, MIS OCC.', '9530413876', null, 'MARY JANE R. SAMSONA', 'CAHAYAG, TUDELA, MIS. OCC.', '9530413876', '1', 'Ramil, Daniela M..jpg', null, null);
INSERT INTO `members` VALUES ('24', null, 'MADLUS', 'ROSITA', 'CABATUAN', 'NOV. 20, 1957', '1957-11-20', 'CAHAYAG, TUDELA', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9508001582', null, 'ROSELYN M. FUENTES', 'NAPUROG, TUDELA, MIS. OCC', '9664732602', '1', 'Madlus, Rosita C..jpg', null, null);
INSERT INTO `members` VALUES ('25', null, 'MADLUS', 'AILEEN', 'ANTALAS', 'NOV. 04, 1990', '1990-11-04', 'DAGATAN, SOMINOT, ZDS', 'F', 'MARRIED', '-', 'BHW', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9556250336', null, 'RICKY C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '9107285590', '1', 'Madlus, Aileen A..jpg', null, null);
INSERT INTO `members` VALUES ('26', null, 'MADLUS', 'BOB', 'MACAN', 'JUL. 23, 1976', '1976-07-23', 'CAHAYAG, TUDELA', 'M', 'MARRIED', 'O', 'CVO', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'WARREN C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madlus, Bob M..jpg', null, null);
INSERT INTO `members` VALUES ('27', null, 'MADLUS', 'ELIEZER ', 'BLANCAR', 'JAN. 12, 1978', '1978-01-12', 'SINACABAN, MIS. OCC.', 'M', 'MARRIED', 'O', 'BRGY. KAGAWAD', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9051715612', null, 'LORENA V. MADLUS', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9977287605', '1', 'Madlus, Eliezer  B..jpg', null, null);
INSERT INTO `members` VALUES ('28', null, 'MADLUS', 'GENALYN', 'NAVALES', 'NOV. 02, 1986', '1986-11-02', 'MAMPAYAG, MANOLO FORTICH, BUKIDNON', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MAMERLITO C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madlus, Genalyn N..jpg', null, null);
INSERT INTO `members` VALUES ('29', null, 'PAROJINOG', 'MAE  ', 'GOMONOD', 'MAY 31, 1995', '1995-05-31', 'CAHAYAG, TUDELA', 'F', 'MARRIED', 'A', 'BRGY. DAY CARE WORKER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'SWERWIN N. PAROJINOG', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Parojinog, Mae   G..jpg', null, null);
INSERT INTO `members` VALUES ('30', null, 'RECOLITO', 'JESSIE', 'ANINO', 'DEC. 13, 1987', '1987-12-13', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'BPAT', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9097704490', null, 'AURELIA T. MAGANTE', 'CAHAYAG, TUDELA, MIS. OCC.', '9097704490', '1', 'Recolito, Jessie A..jpg', null, null);
INSERT INTO `members` VALUES ('31', null, 'LAGUITAO', 'EDDY', 'SOL', 'NOV. 21, 1986', '1986-11-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9121298489', null, 'RECAJAIN S. LAGUITAO', 'CAHAYAG, TUDELA, MIS. OCC.', '9121298489', '1', 'Laguitao, Eddy S..jpg', null, null);
INSERT INTO `members` VALUES ('32', null, 'LAGUITAO', 'ALEX', 'GOMONOD', 'JUL. 07, 1992', '1992-07-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'B+', 'BPAT', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9813600188', null, 'GENELYN R. MAMACANG', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '9813600188', '1', 'Laguitao, Alex G..jpg', null, null);
INSERT INTO `members` VALUES ('33', null, 'IMBOY', 'DELFIN', 'MAHINAY', 'DEC. 22, 1968', '1968-12-22', 'CABOL-ANONAN, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', '-', '-', null, 'ELISA M. EMBOY', 'P-2, CABOL-ANONAN, TUDELA, MIS. OCC.', '9624201427', '1', 'Imboy, Delfin M..jpg', null, null);
INSERT INTO `members` VALUES ('34', null, 'GUMAAT', 'LIZA', 'BLANCAR', 'JUN. 05, 1972', '1972-06-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'UTILITY', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'CHRISALDE B. GUMAAT', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gumaat, Liza B..jpg', null, null);
INSERT INTO `members` VALUES ('35', null, 'SADERA', 'MARUEL ', 'ACURAM', 'APR. 27, 1983', '1983-04-27', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'BRGY, KAGAWAD', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MARYJIL QUENNIE SADERA', 'CAHAYAG, TUDELA, MIS. OCC.', '9502263795', '1', 'Sadera, Maruel  A..jpg', null, null);
INSERT INTO `members` VALUES ('36', null, 'RUBIO', 'JEFREY', 'GOMONOG', 'AUG. 17, 2002', '2002-08-17', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'LINA G. RUBIO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Rubio, Jefrey G..jpg', null, null);
INSERT INTO `members` VALUES ('37', null, 'PALMA', 'ANDY', 'MAGABANUA', 'DEC. 10, 1979', '1979-12-10', 'DIATAGON LIANGA, ZDS', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', 'LABOR', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9268754718', null, 'ALLYN B. PALMA', 'TUDELA, MIS. OCC.', '-', '1', 'Palma, Andy M..jpg', null, null);
INSERT INTO `members` VALUES ('38', null, 'MAGLANGIT', 'REY', 'TOSTOLADO', 'DEC. 15, 1983', '1983-12-15', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9538972831', null, 'JESILYN PATRIA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Maglangit, Rey T..jpg', null, null);
INSERT INTO `members` VALUES ('39', null, 'MAGLANGIT', 'MELSON', 'SOL', 'SEP. 15, 1978', '1978-09-15', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9502615737', null, 'ELLEN LAGAT MAGLANGIT', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Maglangit, Melson S..jpg', null, null);
INSERT INTO `members` VALUES ('40', null, 'NOLASCO', 'EMMA', 'MAGLANGIT', 'FEB. 04, 1972', '1972-02-04', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'TRINA M. NOLASCO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '930007765', '1', 'Nolasco, Emma M..jpg', null, null);
INSERT INTO `members` VALUES ('41', null, 'NAMOCO', 'ROBERTA', 'BLANCAR', 'OCT. 20, 1945', '1945-10-20', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-3', '-', null, 'GRACE B. NAMOCO', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Namoco, Roberta B..jpg', null, null);
INSERT INTO `members` VALUES ('42', null, 'NAMOCO', 'GRACE', 'BLANCAR', 'FEB. 14, 1979', '1979-02-14', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-3', '-', null, 'JOCELYN P. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '9308176609', '1', 'Namoco, Grace B..jpg', null, null);
INSERT INTO `members` VALUES ('43', null, 'NOLASCO', 'JAYLO', 'MAGLANGIT', 'FEB. 06, 2002', '2002-02-06', 'QUEZON CITY', 'M', 'SINGLE', '-', 'CVO', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'EMMA M. NOLASCO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Nolasco, Jaylo M..jpg', null, null);
INSERT INTO `members` VALUES ('44', null, 'RECOLITO', 'RITCHIE', 'ARCENO', 'JUN. 05, 1986', '1986-06-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ROSE R. VECENTE', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Recolito, Ritchie A..jpg', null, null);
INSERT INTO `members` VALUES ('45', null, 'REBLINGCA', 'VERVIC MARIE', 'PAHAYAC', 'FEB. 01, 2003', '2003-02-01', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JEFERSON P. REBLINGCA', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Reblingca, Vervic Marie P..jpg', null, null);
INSERT INTO `members` VALUES ('46', null, 'PEDRITA', 'KRISTINE ANNE', 'GOMONOD', 'NOV. 23, 2001', '2001-11-23', 'JOSE REYES MED. CENTER, MANILA', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', 'STUDENT', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9683014713', null, 'RUSSEL G. PEDRITA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Pedrita, Kristine Anne G..jpg', null, null);
INSERT INTO `members` VALUES ('47', null, 'RUBIO', 'LINA ', 'GOMONOD', 'JUL. 21, 1981', '1981-07-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'REGIE GOMONOD', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Rubio, Lina  G..jpg', null, null);
INSERT INTO `members` VALUES ('48', null, 'REBLINGCA', 'JEFERSON', 'PAHAYAC', 'JUN. 17, 2000', '2000-06-17', 'TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'SK. KAGAWAD', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9813651979', null, 'OLIVER H. REBLINGCA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Reblingca, Jeferson P..jpg', null, null);
INSERT INTO `members` VALUES ('49', null, 'REBLINGCA', 'OLIVER', 'HALANDONI', 'FEB. 07, 1980', '1980-02-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'BPAT', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9813651979', null, 'MARVIC P. REBLINGCA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Reblingca, Oliver H..jpg', null, null);
INSERT INTO `members` VALUES ('50', null, 'PAHAYAC', 'SATURNINA', 'LAGUITAO', 'JUN. 04, 1936', '1936-06-04', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JEFERSON P. REBLINGCA', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Pahayac, Saturnina L..jpg', null, null);
INSERT INTO `members` VALUES ('51', null, 'PALER', 'EMELIE', 'YECYEC', 'JAN. 07, 1970', '1970-01-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9482915407', null, 'ELLYM Y. PALER', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Paler, Emelie Y..jpg', null, null);
INSERT INTO `members` VALUES ('52', null, 'ACURAM', 'DANILO', 'SOL', 'JUN. 21, 1975', '1975-06-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9269541729', null, 'KEVIN N. ACURAM', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9269547129', '1', 'Acuram, Danilo S..jpg', null, null);
INSERT INTO `members` VALUES ('53', null, 'MADLUS', 'LORENA', 'VILLARTA', 'FEB. 13, 1975', '1975-02-13', 'BACOLOD, LANAO DEL NORTE', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9977287605', null, 'ELIEZER B. MADLUS', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9051715612', '1', 'Madlus, Lorena V..jpg', null, null);
INSERT INTO `members` VALUES ('54', null, 'RUBIO ', 'NELSON', 'NAMOCO', 'MAR. 09, 1989', '1989-03-09', 'TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9183612438', null, 'NESTOR RUBIO', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Rubio , Nelson N..jpg', null, null);
INSERT INTO `members` VALUES ('55', null, 'PORMENTO', 'SULPECIO', 'BAHI-AN', 'SEP. 10, 1940', '1940-09-10', 'TABU-O, JIMNENEZ, MIS. OCC.', 'M', 'WIDOW', 'O', 'REGISTERED VOTER', 'FARMER', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'GONDELINA P. SANCHEZ', 'CAHAYAG, TUDELA, MIS. OCC.', '0945718847', '1', 'Pormento, Sulpecio B..jpg', null, null);
INSERT INTO `members` VALUES ('56', null, 'RUFO', 'NEMESIO', 'PINARANDA', 'OCT. 31, 1959', '1959-10-31', 'SINONOC, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'BELEN ABELLANO', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Rufo, Nemesio P..jpg', null, null);
INSERT INTO `members` VALUES ('57', null, 'YECYEC', 'NORBERTO', 'BALAGUSTE', 'JAN. 06, 1958', '1958-01-06', 'CAHAYAG, TUDELA MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'FARMER', '7', 'P-3 CAHAYAG, TUDELA, MIS. OCC.', '9154557798', null, 'JULIETA V. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '09154557798', '1', 'Yecyec, Norberto B..jpg', null, null);
INSERT INTO `members` VALUES ('58', null, 'SANDULAN', 'MARIALIZA', 'YECYEC', 'MAY 09, 1996', '1996-05-09', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9754929283', null, 'RODERICK B. SANDULAN', 'DUMAGOC, PAGADIAN CTY, ZDS.', '09307481052', '1', 'Sandulan, Marializa Y..jpg', null, null);
INSERT INTO `members` VALUES ('59', null, 'NAMOCO', 'PANFILA', 'SADERA', 'MAR. 23, 1938', '1938-03-23', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9269547129', null, 'KEVIN N. ACURAM', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09269547129', '1', 'Namoco, Panfila S..jpg', null, null);
INSERT INTO `members` VALUES ('60', null, 'ABELLANO', 'BELEN', 'ACURAM', 'DEC. 25, 1979', '1979-12-25', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'NEMESIO P. RUFO', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Abellano, Belen A..jpg', null, null);
INSERT INTO `members` VALUES ('61', null, 'MADULA', 'LOLITA', 'QUINTAS', 'AUG. 03, 1960', '1960-08-03', 'DELA PAS, CLARIN, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'RICARDO C. MADULA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Lolita Q..jpg', null, null);
INSERT INTO `members` VALUES ('62', null, 'EGAM', 'WEENA', 'SALOMON', 'OCT. 21, 1985', '1985-10-21', 'TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JOSEPH J. EGAM', 'CAHAYAG, TUDELA, MIS. OCC.', '09756354702', '1', 'Egam, Weena S..jpg', null, null);
INSERT INTO `members` VALUES ('63', null, 'TRASPORTES', 'CANDELARIA', 'NAMOCO', 'FEB. 02, 1972', '1972-02-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9269547129', null, 'KEVIN N. ACURAM', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9269547129', '1', 'Trasportes, Candelaria N..jpg', null, null);
INSERT INTO `members` VALUES ('64', null, 'YECYEC', 'JULIETA', 'VELLARTA', 'JAN. 24, 1961', '1961-01-24', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9154557798', null, 'NORBERTO S. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '091545577898', '1', 'Yecyec, Julieta V..jpg', null, null);
INSERT INTO `members` VALUES ('65', null, 'BLANCAR', 'JERRY', 'YECYEC', 'NOV. 19, 1966', '1966-11-19', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'BPAT', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ROSALITA C. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09460614706', '1', 'Blancar, Jerry Y..jpg', null, null);
INSERT INTO `members` VALUES ('66', null, 'SOL', 'LANDO', 'TEMACAS', 'FEB. 07, 1973', '1973-02-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9630921689', null, 'EMERITA MAGLASANG', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Sol, Lando T..jpg', null, null);
INSERT INTO `members` VALUES ('67', null, 'YECYEC', 'AURELIO', 'LAGIO', 'FEB. 18, 1960', '1960-02-18', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'AB', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MARIALITA Y. SANDULAN', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09754929283', '1', 'Yecyec, Aurelio L..jpg', null, null);
INSERT INTO `members` VALUES ('68', null, 'SAMSONA', 'MARY JANE', 'RAMIL', 'FEB. 07, 1986', '1986-02-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9530413876', null, 'EDWIN M. CUAL', 'CAHAYAG, TUDELA, MIS. OCC.', '09530413876', '1', 'Samsona, Mary Jane R..jpg', null, null);
INSERT INTO `members` VALUES ('69', null, 'YECYEC', 'CHRISTOPHER', 'LAGUITAO', 'OCT. 28, 1984', '1984-10-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'B+', 'REGISTERED VOTER', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9958096536', null, 'CARMEN R. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '09958096536', '1', 'Yecyec, Christopher L..jpg', null, null);
INSERT INTO `members` VALUES ('70', null, 'YECYEC', 'CONCHITA', 'SALAGUSTE', 'SEP. 04, 1964', '1964-09-04', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'BRYAN S. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Yecyec, Conchita S..jpg', null, null);
INSERT INTO `members` VALUES ('71', null, 'YECYEC', 'NOEL', 'LAGO', 'SEP. 23, 1974', '1974-09-23', 'LIBERTAD BAJO, SINACABAN, MIS. OCC.', 'M', 'SINGLE', 'B', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ELLYN Y. PALER', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09703572252', '1', 'Yecyec, Noel L..jpg', null, null);
INSERT INTO `members` VALUES ('72', null, 'SADERA', 'MARY JIL QUENNIE', 'ACURAM', 'NOV. 10, 2000', '2000-11-10', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'LIVE-IN', 'O+', 'REGISTERED VOTER', 'STUDENT', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '95022637945', null, 'CHRISTOPHER T. MAISA', 'P-3, NAILON, TUDELA, MIS. OCC,', '09097983693', '1', 'Sadera, Mary Jil Quennie A..jpg', null, null);
INSERT INTO `members` VALUES ('73', null, 'SADERA', 'MODESTA', 'BLANCAR', 'JAN. 15, 1959', '1959-01-15', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9483172864', null, 'MARYJIL QUENNIE SADERA', 'CAHAYAG, TUDELA, MIS. OCC.', '09502263795', '1', 'Sadera, Modesta B..jpg', null, null);
INSERT INTO `members` VALUES ('74', null, 'SADERA', 'TERCISA', 'BLANCAR', 'FEB. 18, 1956', '1956-02-18', 'COLAMBUTAN SETTLEMENT, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JERAMAI C. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Sadera, Tercisa B..jpg', null, null);
INSERT INTO `members` VALUES ('75', null, 'MACAN', 'JEOFFREY', 'HAMODION', 'DEC. 05, 2002', '2002-12-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'A+', 'SK CHAIRMAN', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9505294656', null, 'MARILOU H. MACAN', 'SAN NICOLAS, TUDELA, MIS. OCC.', '-', '1', 'Macan, Jeoffrey H..jpg', null, null);
INSERT INTO `members` VALUES ('76', null, 'MANGIN', 'JOCELYN', 'VERAS', 'OCT. 27, 1972', '1972-10-27', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O+', 'REGISTERED VOTER', 'UTILITY', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9659650368', null, 'ROSITO C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '098170734', '1', 'Mangin, Jocelyn V..jpg', null, null);
INSERT INTO `members` VALUES ('77', null, 'MAMACANG', 'GENELYN', 'REBLINGCA', 'SEP. 02, 1997', '1997-09-02', 'SM LAO GENERAL HOSPITAL, OZAMIZ CITY', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9813600188', null, 'ALEX G. LAGUITAO', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '09813600188', '1', 'Mamacang, Genelyn R..jpg', null, null);
INSERT INTO `members` VALUES ('78', null, 'MALIMIT', 'MARICEL', 'REBLINGCA', 'NOV. 29, 1982', '1982-11-29', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', '-', '9502772145', null, 'JERECHO REBLINGCA', '-', '-', '1', 'Malimit, Maricel R..jpg', null, null);
INSERT INTO `members` VALUES ('79', null, 'DAISON', 'MELITONA', 'LAGO', 'OCT. 29, 1940', '1940-10-29', 'MAIKAY, TUDELA, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'EMELIE Y. PALER', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09482915407', '1', 'Daison, Melitona L..jpg', null, null);
INSERT INTO `members` VALUES ('80', null, 'EGAM', 'ELVIRA', 'EGAR', 'MAY 16, 1973', '1973-05-16', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'BRGY. KAGAWAD', '-', '7', '-', '9102183260', null, 'DANILO V. EGAM', 'CAHAYAG, TUDELA, MIS. OCC.', '09639380462', '1', 'Egam, Elvira E..jpg', null, null);
INSERT INTO `members` VALUES ('81', null, 'ESTOMATA', 'ALLAN', 'FUDALAN', 'MAY 9, 1981', '1981-05-09', 'TANGNAN, PANGLAO, BOHOL', 'M', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9558453892', null, 'ALLAN FUDALAN ESTOMATA', 'CAHAYAG, TUDELA, MIS. OCC.', '09558453892', '1', 'Estomata, Allan F..jpg', null, null);
INSERT INTO `members` VALUES ('82', null, 'FRANSICSO', 'LESLEH', 'LLORANDO', 'NOV. 13, 1981', '1981-11-13', 'PADADA DEL SUR', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9264213164', null, 'JOEL R. GOMONOD', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09264213164', '1', 'Fransicso, Lesleh L..jpg', null, null);
INSERT INTO `members` VALUES ('83', null, 'TAGANAHAN', 'LOURDESITA', 'GUMONOD', 'OCT. 05, 1961', '1961-10-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'BHW', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JAY G. TAGANAHAN', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09304354944', '1', 'Taganahan, Lourdesita G..jpg', null, null);
INSERT INTO `members` VALUES ('84', null, 'PATRIA', 'JESILYN', 'BLANCAR', 'FEB. 11, 1992', '1992-02-11', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9532730484', null, 'REY MAGLANGIT', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Patria, Jesilyn B..jpg', null, null);
INSERT INTO `members` VALUES ('85', null, 'PEDRITA', 'RUSSEL', 'GOMONOD', 'JAN. 15, 2004', '2004-01-15', 'NAPUROG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O+', 'REGISTERED VOTER', 'STUDENT', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '94795221602', null, 'ROSEMARIE LACSADO', 'TANGUB CITY, MIS. OCC.', '09672404091', '1', 'Pedrita, Russel G..jpg', null, null);
INSERT INTO `members` VALUES ('86', null, 'JALALON', 'KERETH JEAREM', 'MACALIB-OG', 'MAR. 4, 1999', '1999-03-04', 'MIDSALIP, ZDS.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', 'FARMER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9850083568', null, 'TRINA M. NOLASCO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Jalalon, Kereth Jearem M..jpg', null, null);
INSERT INTO `members` VALUES ('87', null, 'EGAM', 'JESUS', 'VILLASIS', 'MAY 6 , 1960', '1960-05-06', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9755740318', null, '-', '-', '-', '1', 'Egam, Jesus V..jpg', null, null);
INSERT INTO `members` VALUES ('88', null, 'CLAROS', 'LIEZEL', 'SUNGCALANG', 'JAN. 29, 1976', '1976-01-29', 'PIÑAN, ZAMBO. DEL NORTE', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'BOB M. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Claros, Liezel S..jpg', null, null);
INSERT INTO `members` VALUES ('89', null, 'MADLUS', 'JOEFFREY', 'MANGIN', 'DEC. 05, 2002', '2002-12-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'SK KAGAWAD', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ROSITO C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '09659650683', '1', 'Madlus, Joeffrey M..jpg', null, null);
INSERT INTO `members` VALUES ('90', null, 'EGAM', 'DANIELO', 'VILLASES', 'APR. 27, 1970', '1970-04-27', '-', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ELVIRA E. EGAM', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Egam, Danielo V..jpg', null, null);
INSERT INTO `members` VALUES ('91', null, 'GOMONOD', 'JAIME', 'CABATUAN', 'JUN. 02, 1965', '1965-06-02', 'TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MARY JANE T. GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09207284743', '1', 'Gomonod, Jaime C..jpg', null, null);
INSERT INTO `members` VALUES ('92', null, 'BLANCAR', 'ROSALITA', 'CAGOD', 'MAR. 07, 1966', '1966-03-07', 'JOSIFENA, ZAMBO SUR.', 'F', 'MARRIED', 'O', 'BRGY. UTILITY', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JERAMAI C. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Blancar, Rosalita C..jpg', null, null);
INSERT INTO `members` VALUES ('93', null, 'GOMONOD', 'VIRGINIA', 'BINTOLAN', 'APR. 20, 1957', '1957-04-20', 'MOLAVE ZDS', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'BENIGNO SOL GOMONOD', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gomonod, Virginia B..jpg', null, null);
INSERT INTO `members` VALUES ('94', null, 'BLANCAR', 'JERAMAI', 'CAGOD', 'APR. 25, 2000', '2000-04-25', 'TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'SK KAGAWAD', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9754925846', null, 'ROSALITA C. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Blancar, Jeramai C..jpg', null, null);
INSERT INTO `members` VALUES ('95', null, 'BLANCAR', 'JEROME', 'CAGOD', 'JUN. 08, 1997', '1997-06-08', '-', 'M', '-', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'GINA D. GALORIO', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '096355890005', '1', 'Blancar, Jerome C..jpg', null, null);
INSERT INTO `members` VALUES ('96', null, 'MACAN', 'JULIA', 'NAMOCO', 'JAN. 28, 1940', '1940-01-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', 'O+', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9505294565', null, 'JEOFFREY H. MACAN', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Macan, Julia N..jpg', null, null);
INSERT INTO `members` VALUES ('97', null, 'SALAGUSTE', 'REYMART', 'ARCALA', 'APR. 08, 2003', '2003-04-08', 'CARMEN, CAGAYAN DE ORO CITY', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', '-', '-', null, 'MEA ANN LARA', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Salaguste, Reymart A..jpg', null, null);
INSERT INTO `members` VALUES ('98', null, 'TUBIGON', 'JEREMIS', 'DIONSON', 'SEP. 25, 1978', '1978-09-25', 'TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'TEACHER', '7', 'BASIRANG, TUDELA, MIS. OCC.', '9302023363', null, 'ROSLYN S. TUBIGON', 'BASIRANG, TUDELA, MIS. OCC.', '09187004085', '1', 'Tubigon, Jeremis D..jpg', null, null);
INSERT INTO `members` VALUES ('99', null, 'TUBIGON', 'ROSLYN', 'SINGIDAS', 'APR. 13, 1982', '1982-04-13', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'TEACHER', '7', 'BASIRANG, TUDELA, MIS. OCC.', '9187004085', null, 'JEMERIS D. TUBIGON', 'BASIRANG, TUDELA, MIS. OCC.', '09302023363', '1', 'Tubigon, Roslyn S..jpg', null, null);
INSERT INTO `members` VALUES ('100', null, 'ROMERO', 'ERIK DONALD', 'ABONG', 'APR. 20, 1986', '1986-04-20', 'MOLAVE ZDS', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9465106952', null, 'ROCHIE MAE S. ROMERO', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09101630364', '1', 'Romero, Erik Donald A. .jpg', null, null);
INSERT INTO `members` VALUES ('101', null, 'SINGIDAS', 'JOSEFINA', 'TARCULAS', 'JUL. 02, 1961', '1961-07-02', 'BAYBAY, LEYTE', 'F', 'MARRIED', 'A+', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9507766566', null, 'ROLANDO P. SINGIDAS', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09508001582', '1', 'Singidas, Josefina T..jpg', null, null);
INSERT INTO `members` VALUES ('102', null, 'GOMONOD', 'JUNNIFER', 'BENTULAN', 'AUG. 14, 1980', '1980-08-14', 'TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9652159510', null, 'EVELYN GOMONOD ', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09652159510', '1', 'Gomonod, Junnifer B..jpg', null, null);
INSERT INTO `members` VALUES ('103', null, 'GOMONOD', 'LIZA', 'DURA', 'JAN. 22, 1969', '1969-01-22', 'SEÑOR, SINCABAN, MIS. OCC.', 'F', 'WIDOW', 'O', 'BRGY. KAGAWAD', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9552354794', null, 'CHRISTY JOY G. DAHUYAG', 'CAHAYAG, TUDELA, MIS. OCC.', '09569665573', '1', 'Gomonod, Liza D..jpg', null, null);
INSERT INTO `members` VALUES ('104', null, 'GUMONOD', 'JUDITH', 'DURA', 'JUL. 26, 1989', '1989-07-26', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O+', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9067302125', null, 'DENNIS M. BALANAY', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09753000163', '1', 'Gumonod, Judith D..jpg', null, null);
INSERT INTO `members` VALUES ('105', null, 'GUMAAT', 'CHRISALDE', 'BLANCAR', 'DEC. 23, 1998', '1998-12-23', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9679572831', null, 'JESSEL MAE Q. MACALISANG', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gumaat, Chrisalde B..jpg', null, null);
INSERT INTO `members` VALUES ('106', null, 'YECYEC', 'JOCELYN', 'LAGUITAO', 'NOV. 02, 1977', '1977-11-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9958096539', null, 'CHRISTOPHER L. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '09958096536', '1', 'Yecyec, Jocelyn L..jpg', null, null);
INSERT INTO `members` VALUES ('107', null, 'MADULA', 'CATALINA', 'EGAM', 'APR. 30, 1951', '1951-04-30', 'TUDELA, MIS. OCC.', 'F', 'WIDOW', 'B', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'NENA M. PASTERA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09129507554', '1', 'Madula, Catalina E..jpg', null, null);
INSERT INTO `members` VALUES ('108', null, 'JUNGCO', 'ROCEL JADE', 'BAYA', 'JUL. 07, 1991', '1991-07-07', 'UPPER TIPARAK, TAMBULIG, ZDS', 'M', 'MARRIED', 'O+', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9161518236', null, 'GLECEYL Y. JUNGCO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09362417841', '1', 'Jungco, Rocel Jade B..jpg', null, null);
INSERT INTO `members` VALUES ('109', null, 'TALABA', 'SOCORRO', 'BLANCAR', 'MARCH', null, 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'DENNIS TALABA', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '09969059971', '1', 'Talaba, Socorro B..jpg', null, null);
INSERT INTO `members` VALUES ('110', null, 'TOSLOLADO', 'ARTURO', 'SADERA', 'AUG. 08, 1961', '1961-08-08', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'A', 'CVO', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '935883285', null, 'IRISH M. TOSLOLADO', 'CAHAYAG, TUDELA, MIS. OCC.', '0935883285', '1', 'Toslolado, Arturo S..jpg', null, null);
INSERT INTO `members` VALUES ('111', null, 'TOSLOLADO', 'IRISH', 'MAGLASANG', 'APR. 09, 1990', '1990-04-09', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'A', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9708620499', null, 'ARJUN M. TOSLOLADO', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Toslolado, Irish M..jpg', null, null);
INSERT INTO `members` VALUES ('112', null, 'PATRIA', 'JAY AR', 'BLANCAR', 'NOV. 08, 2004', '2004-11-08', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9532730484', null, 'JESILYN PATRIA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Patria, Jay Ar B..jpg', null, null);
INSERT INTO `members` VALUES ('113', null, 'PAROJINOG', 'SHERWIN', 'NAMUAG', 'MAR. 02, 1993', '1993-03-02', 'P-3, SILONGON', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9168762369', null, 'MAE G. PAROJINOG', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Parojinog, Sherwin N..jpg', null, null);
INSERT INTO `members` VALUES ('114', null, 'MAGLANGIT', 'HERMIS', 'SOL', 'DEC. 14, 1982', '1982-12-14', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O+', 'REGISTERED VOTER', 'P', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9515634719', null, 'MILYN ERANDIO ANCILLA', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Maglangit, Hermis S..jpg', null, null);
INSERT INTO `members` VALUES ('115', null, 'MADULA', 'LEO', 'EGAM', 'MAR. 31, 1975', '1975-03-31', 'BACOLOD, LANAO DEL NORTE', 'M', 'MARRIED', 'B', 'REGISTERED VOTER', 'DRIVER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9506456486', null, 'CATALINA E. MADULA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Leo E..jpg', null, null);
INSERT INTO `members` VALUES ('116', null, 'GOMONOD', 'FLAVIANA', 'TOSLOLADO', 'JAN. 02, 1966', '1966-01-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'A', 'BRGY. KAGAWAD', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9508001582', null, 'JOEFIL T. GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09488703311', '1', 'Gomonod, Flaviana T..jpg', null, null);
INSERT INTO `members` VALUES ('117', null, 'GOMONOD', 'GREATCHEN', 'TOSLOLADO', 'DEC. 26, 1989', '1989-12-26', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9971489429', null, 'LEOLA GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09163881730', '1', 'Gomonod, Greatchen T..jpg', null, null);
INSERT INTO `members` VALUES ('118', null, 'GOMONOD', 'JUBY', 'BENTULAN', 'OCT. 21, 1978', '1978-10-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9755740318', null, 'ELSA E. GOMONOD', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09755740318', '1', 'Gomonod, Juby B..jpg', null, null);
INSERT INTO `members` VALUES ('119', null, 'TOSLOLADO', 'MARCELINA', 'SADERA', 'APR. 10, 1936', '1936-04-10', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MELODIE G. TOSLOLADO', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Toslolado, Marcelina S..jpg', null, null);
INSERT INTO `members` VALUES ('120', null, 'TOSLOLADO', 'MARVIE', 'HUGO', 'SEP. 28, 1984', '1984-09-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9755255363', null, 'PRINCESS MARVIE D. TOSLOLADO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Toslolado, Marvie H..jpg', null, null);
INSERT INTO `members` VALUES ('121', null, 'CABATUAN', 'FELIX', 'GOMONOD', 'APR. 22, 1955', '1955-04-22', 'BONGABONG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'A', 'REGISTERED VOTER', 'FARMER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '963925946', null, 'MERLIN DAJAO CABATUAN', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Cabatuan, Felix G..jpg', null, null);
INSERT INTO `members` VALUES ('122', null, 'CABARSE', 'BELEN', 'GOMONOD', 'NOV. 10, 1973', '1973-11-10', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'AB+', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9309846690', null, 'ALEJO Q. CABARSE', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09097551584', '1', 'Cabarse, Belen G..jpg', null, null);
INSERT INTO `members` VALUES ('123', null, 'TALABA', 'DENNIS', 'BLANCAR', 'MAR. 12, 1980', '1980-03-12', 'TINAGO, OZAMIZ CITY, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', 'FARMER', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'SOCORRO TALABA', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Talaba, Dennis B..jpg', null, null);
INSERT INTO `members` VALUES ('124', null, 'CALANSINGIN', 'ROGER', 'GALLEROS', 'JUL. 13, 1982', '1982-07-13', 'MHARS GEN. HOSPITAL, OZAMIZ CITY, MIS. OCC.', 'M', 'MARRIED', 'A+', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9488703311', null, 'ALFREDA G. CALANSINGIN', 'P-4, CAHAYAN, TUDELA, MIS. OCC.', '-', '1', 'Calansingin, Roger G..jpg', null, null);
INSERT INTO `members` VALUES ('125', null, 'CABATUAN', 'DINAH', 'BALOLONG', 'JUN. 20, 1980', '1980-06-20', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9639480451', null, 'NELSON D. CABATUAN, SR. ', 'CAHAYAG, TUDELA, MIS. OCC.', '09639480451', '1', 'Cabatuan, Dinah B..jpg', null, null);
INSERT INTO `members` VALUES ('126', null, 'CABATUAN', 'AVELINA', 'DAJAO', 'NOV. 11, 1951', '1951-11-11', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '963259046', null, 'FELIX G. CABATUAN', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09639259046', '1', 'Cabatuan, Avelina D..jpg', null, null);
INSERT INTO `members` VALUES ('127', null, 'CABATUAN', 'REYMAR', 'BALOLONG', 'MAR. 10, 2000', '2000-03-10', 'TONGGO, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9639420451', null, 'DINAH B. CABATUAN', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09639480451', '1', 'Cabatuan, Reymar B..jpg', null, null);
INSERT INTO `members` VALUES ('128', null, 'DAISON', 'ARNEL', 'AGOL', 'JAN. 27, 1982', '1982-01-27', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'PWD PRESIDENT', '-', '7', 'P-6, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ARVVINE BERNIDO', 'CAHAYAG, TUDELA, MIS. OCC.', '09350958230', '1', 'Daison, Arnel A..jpg', null, null);
INSERT INTO `members` VALUES ('129', null, 'YECYEC', 'JOCELYN', 'PALER', 'APR. 14, 1969', '1969-04-14', 'DUANGICAN', 'F', 'MARRIED', 'B', 'BRGY. KAGAWAD', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9308176609', null, 'MARK ALBERT YECYEC', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Yecyec, Jocelyn P..jpg', null, null);
INSERT INTO `members` VALUES ('130', null, 'YECYEC', 'JULBERT', 'VILLARTA', 'JUL. 06, 1995', '1995-07-06', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', 'REGISTERED CRIMINOLOGIST', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9154557798', null, 'JULIETA V. YECYEC', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09154557798', '1', 'Yecyec, Julbert V..jpg', null, null);
INSERT INTO `members` VALUES ('131', null, 'GOMONOD', 'EVELYN', 'TAPUT', 'FEB. 12, 1985', '1985-02-12', 'TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9652159510', null, 'JUNNIFER GOMONOD', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gomonod, Evelyn T..jpg', null, null);
INSERT INTO `members` VALUES ('132', null, 'RUBIO', 'NESTOR', 'CABATUAN', 'AUG. 08, 1958', '1958-08-08', 'COLUPAN SETTLEMENT, TUDELA, MIS. OCC.', 'M', 'WIDOW', 'O', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JEANN RUBIO BALAY', 'CAHAYAG, TUDELA, MIS. OCC.', '09635591462', '1', 'Rubio, Nestor C..jpg', null, null);
INSERT INTO `members` VALUES ('133', null, 'LAGUITAO', 'MERIAM', 'SOL', 'JUN. 06, 1998', '1998-06-06', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9634653931', null, 'EFREN A. RUBINO', 'CAHAYAG, TUDELA, MIS. OCC.', '09121298489', '1', 'Laguitao, Meriam S..jpg', null, null);
INSERT INTO `members` VALUES ('134', null, 'RECOLETO', 'NATIVIDAD', 'ARCENO', 'DEC. 26, 1957', '1957-12-26', 'SAN VICENTE, SINACABAN, MIS. OCC.', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ROSIE R. VICENTE', '-', '-', '1', 'Recoleto, Natividad A..jpg', null, null);
INSERT INTO `members` VALUES ('135', null, 'CABATUAN, SR.', 'NELSON', 'DAJAO', 'NOV. 22, 1976', '1976-11-22', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '96394870451', null, 'DINAH B. CABATUAN', 'CAHAYAG, TUDELA, MIS. OCC.', '09639420451', '1', 'Cabatuan, Sr., Nelson D..jpg', null, null);
INSERT INTO `members` VALUES ('136', null, 'TORSULADO', 'JEAN', 'BESTO', '11-1971', null, 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9066045563', null, 'JEMAR B. TORSULADO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09558477603', '1', 'Torsulado, Jean B..jpg', null, null);
INSERT INTO `members` VALUES ('137', null, 'GOMONOD', 'JESUS', 'SOL', 'JUN. 01, 1968', '1968-06-01', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ANGELENE G. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '09971489429', '1', 'Gomonod, Jesus S..jpg', null, null);
INSERT INTO `members` VALUES ('138', null, 'NOLASCO', 'TRINA', 'MAGLANGIT', '-', null, 'QUEZON CITY', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '938007765', null, 'EMMA M. NOLASCO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Nolasco, Trina M..jpg', null, null);
INSERT INTO `members` VALUES ('139', null, 'CABATUAN', 'MERLIN', 'DAJAO', 'AUG. 27, 1988', '1988-08-27', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'AB', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9122936550', null, 'NARASA D. CABATUAN', 'BASIRANG, TUDELA, MIS. OCC.', '-', '1', 'Cabatuan, Merlin D..jpg', null, null);
INSERT INTO `members` VALUES ('140', null, 'MACAN', 'RUEL', 'NAMOCO', 'OCT. 11, 1980', '1980-10-11', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O+', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9505294565', null, 'MARILOU H. MACAN', 'SAN NICOLAS, TUDELA, MIS. OCC.', '-', '1', 'Macan, Ruel N..jpg', null, null);
INSERT INTO `members` VALUES ('141', null, 'TOSLOLADO', 'JENIO', 'HUGO', 'JUN. 21, 1982', '1982-06-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9380801317', null, 'KRISSY GEN B. TOSLOLADO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Toslolado, Jenio H..jpg', null, null);
INSERT INTO `members` VALUES ('142', null, 'BAHIAN', 'RISTY', 'EMPIL', 'MAY 26, 1989', '1989-05-26', 'TONGGO, TUDELA, MIS. OCC.', 'F', 'MARRIED', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9380801317', null, 'KRISSY GEN B. TOSLOLADO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Bahian, Risty E..jpg', null, null);
INSERT INTO `members` VALUES ('143', null, 'BERNIDO', 'RICHEIL', 'DAISON', 'JUL. 06, 2002', '2002-07-06', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'AB+', 'REGISTERED VOTER', 'STUDENT', '7', 'P-6, CAHAYAG, TUDELA, MIS. OCC.', '9683022303', null, 'ROWELLA BERNIDO', 'CAHAYAG, TUDELA, MIS. OCC.', '09532659591', '1', 'Bernido, Richeil D. .jpg', null, null);
INSERT INTO `members` VALUES ('144', null, 'BLANCAR', 'MARK ROGIE', 'CAGOD', 'JUN. 08, 1997', '1997-06-08', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ROBELYN G. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09979053615', '1', 'Blancar, Mark Rogie C..jpg', null, null);
INSERT INTO `members` VALUES ('145', null, 'TAGANAHAN', 'JAY', 'GOMONOD', 'OCT. 15, 1986', '1986-10-15', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9304354944', null, 'LOURDESTA G. TAGANAHAN', 'CAHAYAG, TUDELA, MIS. OCC.', '09307882344', '1', 'Taganahan, Jay G..jpg', null, null);
INSERT INTO `members` VALUES ('146', null, 'TAGANAHAN, JR.', 'ULDARICO', 'OGAPAY', 'MAR. 03, 1963', '1963-03-03', 'SAN NICOLAS, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JAY G. TAGANAHAN', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09307882344', '1', 'Taganahan, Jr., Uldarico O..jpg', null, null);
INSERT INTO `members` VALUES ('147', null, 'DAJAO ', 'FELY', 'GOMONOD', 'JAN. 28, 1956', '1956-01-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'CRISTITA D, GOMONOD', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Dajao , Fely G..jpg', null, null);
INSERT INTO `members` VALUES ('148', null, 'BERNIDO', 'ARLVINE', 'DAISON', 'FEB 09, 1981', '1981-02-09', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'A+', 'REGISTERED VOTER', '-', '7', 'P-6, CAHAYAG, TUDELA, MIS. OCC.', '9350958230', null, 'ROWELLA BERNIDO', 'CAHAYAG, TUDELA, MIS. OCC.', '09532659591', '1', 'Bernido, Arlvine D..jpg', null, null);
INSERT INTO `members` VALUES ('149', null, 'BALAY', 'LEZLIE', 'RUBIO', 'MAY 30, 1988', '1988-05-30', '-', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9469024146', null, '-', '-', '-', '1', 'Balay, Lezlie R..jpg', null, null);
INSERT INTO `members` VALUES ('150', null, 'LAGUNDAY', 'ALEXES', 'DELPRADO', 'MAR. 14, 1988', '1988-03-14', 'E.B. MAGALONA', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9534193574', null, 'NANCY E. LAGUNDAY', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '09753058535', '1', 'Lagunday, Alexes D..jpg', null, null);
INSERT INTO `members` VALUES ('151', null, 'CANDADO', 'MONICA', 'PALER', 'MAR. 19, 1995', '1995-03-19', 'MALABANG, LANAO DEL NORTE', 'F', 'MARRIED', '-', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9753006078', null, 'JULIETEO P. ACURAM', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09056493894', '1', 'Candado, Monica P..jpg', null, null);
INSERT INTO `members` VALUES ('152', null, 'EGAM', 'KIM JOHN', 'E.', 'SEP. 02, 2003', '2003-09-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9502815211', null, 'ELVIRA E. EGAM', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Egam, Kim John E..jpg', null, null);
INSERT INTO `members` VALUES ('153', null, 'SANCHEZ', 'GONDELINA', 'PORMENTO', 'MAR. 28, 1968', '1968-03-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JOSEPH S. SANCHEZ', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Sanchez, Gondelina P..jpg', null, null);
INSERT INTO `members` VALUES ('154', null, 'ACURAM', 'JEZZEL', 'PALER', 'OCT. 05, 1997', '1997-10-05', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9269546733', null, 'LUZMINDA P. ACURAM', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Acuram, Jezzel P..jpg', null, null);
INSERT INTO `members` VALUES ('155', null, 'ACURAM', 'GUILLERMO', 'PALER', 'DEC. 02, 1978', '1978-12-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'REGISTERED VOTER', 'FARMER/CARPENTER', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JASPER CAHUCOM ACURAM', 'CAHAYAG, TUDELA, MIS. OCC.', '09639231483', '1', 'Acuram, Guillermo P..jpg', null, null);
INSERT INTO `members` VALUES ('156', null, 'ACURAM', 'ALLAN', 'SOL', 'JUL. 18, 1963', '1963-07-18', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'REBECCA P. LAGARE', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09757156136', '1', 'Acuram, Allan S..jpg', null, null);
INSERT INTO `members` VALUES ('157', null, 'ACURAM, JR.', 'DIONSESIO', 'SOL', 'AUG. 07, 1964', '1964-08-07', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ELMER R. ACURAM', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Acuram, Jr., Dionsesio S..jpg', null, null);
INSERT INTO `members` VALUES ('158', null, 'CABATUAN, SR.', 'JEFRE', 'RUBIO', 'APR. 26, 1993', '1993-04-26', 'KATIPUNAN, SINACABAN, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9487240835', null, 'KATHEARINE C. GARCIA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Cabatuan, Sr., Jefre R..jpg', null, null);
INSERT INTO `members` VALUES ('159', null, 'ACURAM', 'MANUEL', 'OCAY', 'AUG. 03, 1980', '1980-08-03', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ERMY ACURAM', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Acuram, Manuel O..jpg', null, null);
INSERT INTO `members` VALUES ('160', null, 'ACURAM', 'LUZMINDA', 'PALER', 'SEP. 24, 1959', '1959-09-24', 'DUANGICAN, TUDELA, MIS. OCC.', 'F', 'WIDOW', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9652171928', null, 'LARELYN P. ACURAM', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Acuram, Luzminda P..jpg', null, null);
INSERT INTO `members` VALUES ('161', null, 'ACURAM', 'LARELYN', 'PALER', 'JAN. 21, 1992', '1992-01-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9758070034', null, 'LUZMINDA P. ACURAM', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Acuram, Larelyn P..jpg', null, null);
INSERT INTO `members` VALUES ('162', null, 'ACURAM', 'JOVENIANO', 'BLANCAR', 'OCT. 15, 1957', '1957-10-15', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MELITONA L. DAISON', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09508001582', '1', 'Acuram, Joveniano B..jpg', null, null);
INSERT INTO `members` VALUES ('163', null, 'SALAGUSTE', 'DESEL', 'PALER', 'JUL. 13, 1989', '1989-07-13', 'MATAMPAY ELAYA LALA, LANAO DEL NORTE', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9753020354', null, 'DARYL PALER SALAGUSTE', 'CAHAYAG, TUDELA, MIS. OCC.', '09753020354', '1', 'Salaguste, Desel P..jpg', null, null);
INSERT INTO `members` VALUES ('164', null, 'AGAWIN', 'LEONORA', 'YECYEC', 'JUN. 14, 1960', '1960-06-14', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'WIDOW', 'B', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9071174210', null, '-', '-', '-', '1', 'Agawin, Leonora Y..jpg', null, null);
INSERT INTO `members` VALUES ('165', null, 'ACURAM', 'PERLA', 'CANUCOM', 'JUN. 29, 1975', '1975-06-29', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'A+', 'WOMEN PRESIDENT', 'HOUSEKEEPER', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9817904483', null, 'GUILLERMO P. ACURMA, JR.', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Acuram, Perla C..jpg', null, null);
INSERT INTO `members` VALUES ('166', null, 'ACURAM', 'MARY CRIS', 'ABAD', 'DEC. 16, 2002', '2002-12-16', 'TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', 'STUDENT', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9982699608', null, 'ELSA A. ACURAM', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09631340531', '1', 'Acuram, Mary Cris A..jpg', null, null);
INSERT INTO `members` VALUES ('167', null, 'ACURAM', 'ELSA', 'ABAD', 'NOV. 25, 1971', '1971-11-25', 'SUDLON, MOLAVE, ZDS', 'F', 'MARRIED', 'O', 'BRGY. KAGAWAD', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9631340531', null, 'MARIO A. ACURAM', 'CAHAYAG, TUDELA, MIS. OCC.', '09606666392', '1', 'Acuram, Elsa A..jpg', null, null);
INSERT INTO `members` VALUES ('168', null, 'MADULA', 'EULYSIS', 'VINSON', 'SEP. 17, 2001', '2001-09-17', 'VALENZUELA CITY', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'CATALINA E. MADULA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Eulysis V..jpg', null, null);
INSERT INTO `members` VALUES ('169', null, 'BERNIDO', 'RUBY', 'MAGHANOY', 'OCT. 1971', null, 'MAIKAY, TUDELA, MIS. OCC.', 'M', 'MARRIED', '-', 'BPAT', '-', '7', 'P-6, CAHAYAG, TUDELA, MIS. OCC.', '9753007113', null, 'ARWINE BERNIDO', 'CAHAYAG, TUDELA, MIS. OCC.', '09350958230', '1', 'Bernido, Ruby M..jpg', null, null);
INSERT INTO `members` VALUES ('170', null, 'BESTO', 'DIOSDADO', 'DALANGIN', 'NOV. 28, 1964', '1964-11-28', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', '-', 'O', 'BPAT', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JERAMAI C. BLANCAR', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09754925846', '1', 'Besto, Diosdado D..jpg', null, null);
INSERT INTO `members` VALUES ('171', null, 'BLANCAR', 'ARNOLD', 'YECYEC', 'JAN. 21, 1970', '1970-01-21', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'CHRISALDE B. GUMAAT', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09679572831', '1', 'Blancar, Arnold Y..jpg', null, null);
INSERT INTO `members` VALUES ('172', null, 'MADLUS', 'JOHN ELIEZER', 'VILLARTA', 'APRIL 08, 2001', '2001-04-08', 'OZAMIZ CITY', 'M', 'SINGLE', 'O+', 'REGISTERED VOTER', 'REGISTERED CRIMINOLOGIST', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9051715612', null, 'LORENA V. MADLUS', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09977287605', '1', 'Madlus, John Eliezer V..jpg', null, null);
INSERT INTO `members` VALUES ('173', null, 'CONO', 'WENDELL', 'SADERA', 'AUG. 02, 2004', '2004-08-02', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'LIVE-IN', 'O', 'REGISTERED VOTER', 'FARMER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9473257176', null, 'HONEYVEL C. ALIMBE', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09264213691', '1', 'Cono, Wendell S..jpg', null, null);
INSERT INTO `members` VALUES ('174', null, 'CABARSE', 'ALEJO', 'QUEROG', 'JUL. 20, 1968', '1968-07-20', 'SILONGON, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'REGISTERED VOTER', 'FARMER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9097551584', null, 'BELEN G. CABARSE', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Cabarse, Alejo Q..jpg', null, null);
INSERT INTO `members` VALUES ('175', null, 'GALLION', 'RED FORD', 'AMABALONG', 'MAR. 04, 1989', '1989-03-04', '-', 'M', '-', '-', 'REGISTERED VOTER', 'LABOR', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9108868523', null, 'EDELYN S. MAGLANGIT', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09067404120', '1', 'Gallion, Red Ford A..jpg', null, null);
INSERT INTO `members` VALUES ('176', null, 'ALIMBE', 'HONEYVEL', 'CABAJOSA', 'NOV. 25, 2004', '2004-11-25', 'STO. NIÑO, ZOMINOT, ZDS', 'F', 'LIVE-IN', 'O+', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9473257176', null, 'WENDELL S. CONO', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09264213691', '1', 'Alimbe, Honeyvel C..jpg', null, null);
INSERT INTO `members` VALUES ('177', null, 'AÑABEZA', 'JULIETO', 'CASTAÑOS', 'JUL. 22, 1983', '1983-07-22', 'CENTRO NAPU, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'O', 'BPAT', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9508001582', null, 'CHRISTINE JOY R. AÑABEZA', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Añabeza, Julieto C..jpg', null, null);
INSERT INTO `members` VALUES ('178', null, 'RECOLETO', 'QUENNIE', 'ANINO', 'FEB. 19, 1999', '1999-02-19', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9505261316', null, 'NINO RENE JOSE C. VAPOR', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Recoleto, Quennie A..jpg', null, null);
INSERT INTO `members` VALUES ('179', null, 'MADULA', 'LYN', 'QUINTAS', 'APR. 21, 2000', '2000-04-21', 'TUDELA, MIS. OCC.', 'F', 'LIVE-IN', 'B', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9512673087', null, 'DANNY A. MONTALBA', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Lyn Q..jpg', null, null);
INSERT INTO `members` VALUES ('180', null, 'MADLUS', 'JASMINE', 'MANGIN', 'JUN. 06, 2006', '2006-06-06', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', 'STUDENT', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9354947276', null, 'JOCELYN M. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '9659650638', '1', 'Madlus, Jasmine M..jpg', null, null);
INSERT INTO `members` VALUES ('181', null, 'SARDAN', 'RONALDO', 'A.', 'FEB. 01, 2005', '2005-02-01', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', '-', '-', null, 'TITA T. ACURAM', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Sardan, Ronaldo A..jpg', null, null);
INSERT INTO `members` VALUES ('182', null, 'YECYEC', 'MARGARITO', 'BENDOY', 'MAR. 31, 1995', '1995-03-31', 'MAIGO, LANAO DEL NORTE', 'M', 'WIDOW', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9303398674', null, 'MARLON C. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Yecyec, Margarito B..jpg', null, null);
INSERT INTO `members` VALUES ('183', null, 'ACURAM', 'AILA MAE', 'CAHUCOM', 'FEB. 08, 2006', '2006-02-08', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', 'STUDENT', '7', 'TUDELA, MIS. OCC.', '-', null, 'PERLA C. ACURAM', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Acuram, Aila Mae C..jpg', null, null);
INSERT INTO `members` VALUES ('184', null, 'NOLASCO', 'MARY GRACE', 'MAGLANGIT', 'JUN. 09, 2005', '2005-06-09', 'QUEZON CITY', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9502549132', null, 'EMMA M. NOLASCO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Nolasco, Mary Grace M..jpg', null, null);
INSERT INTO `members` VALUES ('185', null, 'AVANCEÑA', 'JOSEPHINE', 'GOMONOD', 'NOV. 29, 1997', '1997-11-29', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '9978672304', null, 'LEOLA GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09163817380', '1', 'Avanceña, Josephine G..jpg', null, null);
INSERT INTO `members` VALUES ('186', null, 'ARCILLA', 'MILYN', 'ERANDIO', 'FEB. 01, 1990', '1990-02-01', 'TAYTAY, RIZAL', 'F', 'MARRIED', 'A+', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9515634719', null, 'HERMIS SOL MAGLANGIT', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Arcilla, Milyn E..jpg', null, null);
INSERT INTO `members` VALUES ('187', null, 'MADULA', 'GILBERT', 'EGAM', 'JUL. 11, 1976', '1976-07-11', 'BACOLOD, LANAO DEL NORTE', 'M', 'MARRIED', 'AB', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9260937242', null, 'JINGLE B. MADULA', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Madula, Gilbert E..jpg', null, null);
INSERT INTO `members` VALUES ('188', null, 'MADLUS', 'CHERYL', 'NAVALES', 'MAY 28, 2005', '2005-05-28', 'MANOLO FORTICH, BUKIDNON', 'F', 'SINGLE', '-', 'REGISTERED VOTER', 'STUDENT', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '975144709', null, 'NAMERLITO C. MADLUS', 'CAHAYAG, TUDELA, MIS. OCC.', '09091989852', '1', 'Madlus, Cheryl N..jpg', null, null);
INSERT INTO `members` VALUES ('189', null, 'GOMONOD', 'LEOLOLA', 'TOSLOLADO', 'JUL. 31, 1970', '1970-07-31', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', '-', 'O', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JESUS S. GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09163817380', '1', 'Gomonod, Leolola T..jpg', null, null);
INSERT INTO `members` VALUES ('190', null, 'GOMONOD', 'REGIE', '-', 'APR. 04, 2006', '2006-04-04', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'LINA G. RUBIO', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gomonod, Regie -.jpg', null, null);
INSERT INTO `members` VALUES ('191', null, 'GOMONOD', 'MERIE', 'DAJAO', 'OCT. 11, 1979', '1979-10-11', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ALMA D. GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09098399165', '1', 'Gomonod, Merie D..jpg', null, null);
INSERT INTO `members` VALUES ('192', null, 'GOMONOD', 'PERCY', 'TOSLOLADO', 'FEB. 09, 2000', '2000-02-09', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', 'A', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9753051246', null, 'LEOLA GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '09163817380', '1', 'Gomonod, Percy T..jpg', null, null);
INSERT INTO `members` VALUES ('193', null, 'YECYEC', 'MARK ALBERT', 'PALER', 'JUL. 16, 1996', '1996-07-16', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'JOCELYN YECYEC', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Yecyec, Mark Albert P..jpg', null, null);
INSERT INTO `members` VALUES ('194', null, 'MADLUS', 'WARREN', 'CLAROS', 'JUL. 22, 2005', '2005-07-22', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', '-', 'SK KAGAWAD', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9754918902', null, 'LIEZEL S. CLAROS', 'CAHAYAG, TUDELA, MIS. OCC.', '09754918902', '1', 'Madlus, Warren C..jpg', null, null);
INSERT INTO `members` VALUES ('195', null, 'LAGARE', 'REBECCA', 'PORMENTO', 'APR. 06, 1973', '1973-04-06', 'BUENAVISTA, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'A', 'REGISTERED VOTER', 'HOUSEKEEPER', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'ARNIE P. LAGARE', 'CAHAYAG, TUDELA, MIS. OCC.', '09757156136', '1', 'Lagare, Rebecca P..jpg', null, null);
INSERT INTO `members` VALUES ('196', null, 'GOMONOD', 'ANGELA', 'EGAM', 'JUL. 20, 2005', '2005-07-20', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9755740318', null, 'ELSA E. GOMONOD', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '09755740318', '1', 'Gomonod, Angela E..jpg', null, null);
INSERT INTO `members` VALUES ('197', null, 'GOMONOD', 'ALMA', 'DAJAO', 'OCT. 24, 1973', '1973-10-24', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'CRISTITA D, GOMONOD', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Gomonod, Alma D..jpg', null, null);
INSERT INTO `members` VALUES ('198', null, 'YECYEC', 'GLECERIA', 'ADECER', 'DEC. 21, 1961', '1961-12-21', 'SAN NICOLAS, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'GLECEYL Y. JUNGCO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09362417841', '1', 'Yecyec, Gleceria A..jpg', null, null);
INSERT INTO `members` VALUES ('199', null, 'MAGLANGIT', 'ELLEN', 'LAGAT', 'JUN. 13, 1989', '1989-06-13', 'SILONGON, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'B', 'REGISTERED VOTER', '-', '7', 'CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'MELSON SOL MAGLANGIT', 'CAHAYAG, TUDELA, MIS. OCC.', '-', '1', 'Maglangit, Ellen L..jpg', null, null);
INSERT INTO `members` VALUES ('200', null, 'JUNGCO', 'GLECEYL', 'YECYEC', 'NOV. 25, 1994', '1994-11-25', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'BRGY. SECRETARY', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9362417841', null, 'ROCEL JADE B. JUNGCO', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09161518236', '1', 'Jungco, Gleceyl Y..jpg', null, null);
INSERT INTO `members` VALUES ('201', null, 'YECYEC', 'CARMEN', 'RUBIO', 'MAR. 10, 1991', '1991-03-10', 'SAN LORENZO RUIZ', 'F', 'MARRIED', '-', 'BHW', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9958096536', null, 'CHRISTOPHER L. YECYEC', 'CAHAYAG, TUDELA, MIS. OCC.', '09958096536', '1', 'Yecyec, Carmen R..jpg', null, null);
INSERT INTO `members` VALUES ('202', null, 'MAGLANGIT', 'EDELYN', 'SOL', 'OCT. 25, 1988', '1988-10-25', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'MARRIED', 'O', 'REGISTERED VOTER', 'HOUSEWIFE', '7', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '9067404120', null, 'RED FORD A. GALLION', 'P-2, CAHAYAG, TUDELA, MIS. OCC.', '09108858523', '1', 'Maglangit, Edelyn S..jpg', null, null);
INSERT INTO `members` VALUES ('203', null, 'MAGANTE', 'AURELIA', 'TABATA', 'JUL. 29, 1983', '1983-07-29', 'TUDELA, MIS. OCC.', 'F', 'SINGLE', 'O', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9097704490', null, 'JESSIE A. RECOLETO', 'CAHAYAG, TUDELA, MIS. OCC.', '09097704490', '1', 'Magante, Aurelia T..jpg', null, null);
INSERT INTO `members` VALUES ('204', null, 'MAGADAN', 'MARIA ', 'JAMELO', 'OCT. 28, 1952', '1952-10-28', 'TALAKAC, BUKIDNON', 'F', 'WIDOW', '-', 'REGISTERED VOTER', '-', '7', 'P-3, CAHAYAG, TUDELA, MIS. OCC.', '9121568251', null, 'MERLY M. LUMASAG', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09121568251', '1', 'Magadan, Maria  J..jpg', null, null);
INSERT INTO `members` VALUES ('205', null, 'YECYEC', 'MAYLENE', 'ADECIR', 'MAY 19, 1999', '1999-05-19', 'CAHAYAG, TUDELA, MIS. OCC.', 'F', 'SINGLE', '-', 'REGISTERED VOTER', '-', '7', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '9451666024', null, 'MARIALIZA Y. SANDULAN', 'P-4, CAHAYAG, TUDELA, MIS. OCC.', '09754929283', '1', 'Yecyec, Maylene A..jpg', null, null);
INSERT INTO `members` VALUES ('206', null, 'YECYEC', 'MARLON', 'CAHUCOM', 'APR. 27, 1999', '1999-04-27', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'SINGLE', 'O', 'REGISTERED VOTER', 'O', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '9518835408', null, 'MARGARITO B. YECYEC', 'P-1, CAHAYAG, TUDELA, MIS. OCC', '-', '1', 'Yecyec, Marlon C..jpg', null, null);
INSERT INTO `members` VALUES ('207', null, 'RECOLETO', 'ALFREDO', 'YBLANE', 'MAY. 14, 1960', '1960-05-14', 'CAHAYAG, TUDELA, MIS. OCC.', 'M', 'WIDOW', 'B', 'REGISTERED VOTER', '-', '7', 'P-1, CAHAYAG, TUDELA, MIS. OCC.', '-', null, 'QUINNIE R. VAPOR', '-', '-', '1', 'Recoleto, Alfredo Y..jpg', null, null);
